mobile_splash_splash_request_homepage:
    path:     /hello/{name}
    defaults: { _controller: MobileSplashSplashRequestBundle:Default:index }

mobile_splash_request_add:
    path: /splash/request/add
    defaults:
        _controller: MobileSplashSplashRequestBundle:SplashRequest:add
        
mobile_splash_vendors:
    path: /splash/getVendors/{country_id}
    defaults: {_controller: MobileSplashSplashRequestBundle:SplashRequest:getVendors }