services:
#    mobile_splash_splash_request.example:
#        class: MobileSplash\SplashRequestBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    kernel.listener.acme_foo_exception_listener:
        class: MobileSplash\SplashRequestBundle\Listener\ExceptionListener
        arguments: [@templating, @kernel]
        tags:
        - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
