services:
    unique_event_date_validator:
        class: MobileSplash\SplashRequestBundle\Validator\CheckBgCustomizedFieldsValidator
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            -
                name: validator.constraint_validator
                alias: check_customized_bg_fields